name: flight_reservation
description: "Flight reservation application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  flutter_local_notifications: ^18.0.0
  cupertino_icons: ^1.0.8
  firebase_messaging: ^15.1.3
  intl_utils: ^2.8.7
  pdf: ^3.11.1
  printing: ^5.13.4
  path_provider: ^2.0.11
  flutter_animate: ^3.0.0
  fluttertoast: ^8.0.9
  flutter_easyloading: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl: ^0.19.0
  intl_translation: ^0.20.0

flutter:
  generate: true  # Enables code generation for localization
  uses-material-design: true  # Include material design icons

  assets:
    - assets/images/1.png
    - assets/images/test.png
    - assets/images/booking.png
    - assets/images/world.png
    - assets/images/seat.png
    - assets/images/planeshape.png
    - assets/images/card.png
    - lib/l10n/app_fr.arb
    - lib/l10n/app_en.arb

# Optional: To add custom fonts, you can uncomment the section below
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
